"""empty message

Revision ID: 148e6b524551
Revises: 7b877590fc40
Create Date: 2022-07-28 19:20:25.821254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148e6b524551'
down_revision = '7b877590fc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin2', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('admin3', sa.String(length=30), nullable=True))
        batch_op.drop_column('sysadmins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sysadmins', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('admin3')
        batch_op.drop_column('admin2')

    # ### end Alembic commands ###
