"""empty message

Revision ID: 1b8d8a3688b2
Revises: a31419e3ce21
Create Date: 2022-07-11 16:07:45.084439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8d8a3688b2'
down_revision = 'a31419e3ce21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('whatHasBeenDone', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'whatHasBeenDone')
    # ### end Alembic commands ###
