"""empty message

Revision ID: 338c766cdd14
Revises: f81c672d2f3a
Create Date: 2022-08-01 11:14:16.634746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c766cdd14'
down_revision = 'f81c672d2f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serialNumber', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypervisor', schema=None) as batch_op:
        batch_op.drop_column('serialNumber')

    # ### end Alembic commands ###
