"""empty message

Revision ID: 34df07fa1452
Revises: df8f7b22e945
Create Date: 2022-08-07 14:31:34.781834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34df07fa1452'
down_revision = 'df8f7b22e945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_servers_customer_id_customers'), 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_servers_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
