"""empty message

Revision ID: 4ff8299cf7c1
Revises: 8f79ba094cd0
Create Date: 2022-07-11 13:00:31.834608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff8299cf7c1'
down_revision = '8f79ba094cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'status')
    # ### end Alembic commands ###
