"""empty message

Revision ID: 533b73ad96c3
Revises: a737b4a75510
Create Date: 2022-07-12 08:44:18.094911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533b73ad96c3'
down_revision = 'a737b4a75510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('username', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'username')
    # ### end Alembic commands ###
