"""empty message

Revision ID: 7b877590fc40
Revises: b7fdfcb11420
Create Date: 2022-07-28 16:24:17.849299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b877590fc40'
down_revision = 'b7fdfcb11420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('admin1', sa.String(length=30), nullable=True))
    op.drop_column('customers', 'sysadmins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sysadmins', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('customers', 'admin1')
    # ### end Alembic commands ###
