"""empty message

Revision ID: 8f79ba094cd0
Revises: 94be73a0b2af
Create Date: 2022-07-04 15:54:08.908739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f79ba094cd0'
down_revision = '94be73a0b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.Column('client', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('resolve', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employees_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_1',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('firstName', sa.TEXT(), nullable=True),
    sa.Column('lastName', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=25), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True)
    )
    op.drop_table('work_reports')
    # ### end Alembic commands ###
