"""empty message

Revision ID: a31419e3ce21
Revises: 4ff8299cf7c1
Create Date: 2022-07-11 13:28:28.831015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31419e3ce21'
down_revision = '4ff8299cf7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('reason', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'reason')
    # ### end Alembic commands ###
