"""empty message

Revision ID: a737b4a75510
Revises: 1b8d8a3688b2
Create Date: 2022-07-12 08:30:20.772339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a737b4a75510'
down_revision = '1b8d8a3688b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('createTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'createTime')
    # ### end Alembic commands ###
